Fixed not stopping when moving; Fixed interrupted moving
newAM/idasen pull request #409
Opened 2024-02-08 21:07 UTC by sroebert

After my PR #396 I noticed that my desk is not stopping anymore if pressing stop in Home Assistant. The moving of the desk is also sometimes interrupted. These changes fix these issues, I tested it with Home Assistant and everything seems to be working smoothly again.

I had a local implementation for my own desk which I was using before and the sleep was necessary, but it does not seem to be necessary with the Bleak Bluetooth library.

2024-02-13 02:41 UTC, newAM requested changes
I am noticing a lot of hysteresis after these changes.
It is probably something small, but work is keeping me busy these days and I might not have time to debug for a while.

`main` branch, high to low:

```console
$ poetry run idasen height
0.798 meters
$ poetry run idasen sit
$ poetry run idasen height
0.740 meters
```

`main` branch, low to high:

```console
$ poetry run idasen height
0.678 meters
$ poetry run idasen sit
$ poetry run idasen height
0.740 meters
```

#409, high to low:

```console
$ poetry run idasen height
0.794 meters
$ poetry run idasen sit
$ poetry run idasen height
0.783 meters
```


#409, low to high:

```console
$ poetry run idasen height
0.683 meters
$ poetry run idasen sit
$ poetry run idasen height
0.694 meters
```

2024-02-14 15:04 UTC, sroebert commented
I will have a look at what is causing this.

2024-02-24 15:55 UTC, sroebert commented
Ok, it turned out the delay was still needed when running locally, less so when running via a Bluetooth proxy on esphome. Lowering the delay actually seems to have solved the issues I have seeing. Re-adding the delay also solved the hysteresis. I think it should be good to go now.

2024-02-29 14:59 UTC, sroebert commented
If you have time to test it with your desk, it would be nice to get this through, idasen-ha was already updated to downgrade to 0.11: https://github.com/home-assistant/core/issues/110958, https://github.com/abmantis/idasen-ha/pull/23

2024-03-05 01:16 UTC, newAM approved these changes
Thanks for the fix!

2024-03-05 01:16 UTC, merged